# Generated by Django 3.1.6 on 2021-02-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='toys',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Toy'),
        ),
    ]
